# Generated by Django 4.2.4 on 2023-10-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили пользователей', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
