# Generated by Django 4.2.4 on 2023-10-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Товар корзины', 'verbose_name_plural': 'Товары корзины'},
        ),
    ]
