services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./shop
    container_name: backend
    env_file:
      - ./shop/.env
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    depends_on:
      - db

  celery:
    build:
      context: ./shop
    container_name: celery
    command: celery -A shop worker -l info
    env_file:
      - ./shop/.env
    volumes:
      - ./shop:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: ./shop
    container_name: celery-beat
    command: celery -A shop beat -l info
    env_file:
      - ./shop/.env
    volumes:
      - ./shop:/app
    depends_on:
      - db
      - redis
      - celery

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
    depends_on:
      - backend

volumes:
  pgdata:
  static_volume: