# Generated by Django 4.2.4 on 2023-10-28 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='^[1-9][0-9]?$|^99$')])),
            ],
        ),
    ]
