# Generated by Django 4.2.4 on 2023-10-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_alter_discount_percent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
