# Generated by Django 4.2.4 on 2023-10-28 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_alter_discount_end_alter_discount_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 14, 15, 32, 858718)),
        ),
    ]
