# Generated by Django 4.2.4 on 2023-10-29 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_alter_discount_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AlterField(
            model_name='discount',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 17, 32, 48, 540993)),
        ),
    ]
