# Generated by Django 4.2.4 on 2023-10-29 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_remove_discount_product_alter_discount_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 23, 0, 0, 289778)),
        ),
    ]
