# Generated by Django 4.2.4 on 2023-11-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
