# Generated by Django 4.2.4 on 2023-10-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
    ]
