# Generated by Django 4.2.4 on 2023-10-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', 'man'), ('woman', 'woman'), ('boy', 'boy'), ('girl', 'girl')], max_length=5, null=True, verbose_name='Для кого'),
        ),
    ]
