# Generated by Django 4.2.4 on 2023-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_gender_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman'), ('unisex', 'unisex'), ('boy', 'boy'), ('girl', 'girl'), ('unisex_kids', 'unisex_kids')], max_length=11, verbose_name='Для кого'),
        ),
    ]
