# Generated by Django 4.2.4 on 2023-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_gender_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужчинам'), ('woman', 'Женщинам'), ('boy', 'Мальчикам'), ('girl', 'Девочкам')], max_length=20, verbose_name='Пол'),
        ),
    ]
