# Generated by Django 4.2.4 on 2023-10-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужчинам'), ('Женщинам', 'Женщинам'), ('Мальчикам', 'Мальчикам'), ('Девочкам', 'Девочкам')], max_length=20, verbose_name='Пол'),
        ),
    ]
