# Generated by Django 4.2.4 on 2023-10-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_category_gender_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
    ]
