# Generated by Django 4.2.4 on 2023-10-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проданных товаров'),
        ),
    ]
