# Generated by Django 4.2.4 on 2023-10-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_alter_discount_end'),
        ('products', '0024_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='discounts.discount', verbose_name='Скидка'),
        ),
    ]
