# Generated by Django 4.2.4 on 2023-11-18 16:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(regex='^[1-9][0-9]?$|^99$')])),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(default=datetime.datetime(2023, 11, 18, 16, 30, 49, 711236))),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ('-end',),
            },
        ),
    ]
