# Generated by Django 4.2.4 on 2023-10-28 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(regex='^[1-9][0-9]?$|^99$')]),
        ),
    ]
