# Generated by Django 4.2.4 on 2023-10-28 10:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0023_product_number_of_sold'),
        ('discounts', '0003_delete_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(regex='^[1-9][0-9]?$|^99$')])),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(default='13:27 28-10-2023')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ('-end',),
            },
        ),
    ]
