# Generated by Django 4.2.4 on 2023-10-31 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_alter_discount_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 11, 31, 2, 384166)),
        ),
    ]
