# Generated by Django 4.2.4 on 2023-10-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
        ('cart', '0002_alter_cartproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordering.order'),
        ),
    ]
