# Generated by Django 4.2.4 on 2023-10-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'Фотографии товаров', 'verbose_name_plural': 'Фотографии товаров'},
        ),
    ]
