# Generated by Django 4.2.4 on 2023-10-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_categories_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
