# Generated by Django 4.2.4 on 2023-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_gender_alter_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('man', 'Мужчинам'), ('woman', 'Женщинам'), ('boy', 'Мальчикам'), ('girl', 'Девочкам')], max_length=20, verbose_name='Пол')),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
