# Generated by Django 4.2.4 on 2023-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_gender_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужчинам'), ('woman', 'Женщинам'), ('boy', 'Мальчикам'), ('girl', 'Девочкам')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужчинам'), ('woman', 'Женщинам'), ('boy', 'Мальчикам'), ('girl', 'Девочкам')], max_length=5),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
