# Generated by Django 4.2.4 on 2023-10-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_remove_discount_product_alter_discount_end'),
        ('products', '0023_product_number_of_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='discounts.discount'),
        ),
    ]
